import "./styles.css";
import { AppProviders } from "@/components/providers/app-providers";

// Per-request CSP nonces require dynamic rendering. Without this, Next can serve a
// cached shell whose scripts do not carry the nonce generated by proxy.ts.
export const dynamic = "force-dynamic";

export const metadata = {
  title: "HealthGov Security Console",
  description: "Unified healthcare security, compliance, clinical and device posture",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="en" suppressHydrationWarning><body><AppProviders>{children}</AppProviders></body></html>;
}
