apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../components/interoperability
  - ../../components/iomt
  - ../../components/saas
  - ../../components/ai
patches:
  - target: { kind: Deployment, name: phi-classifier }
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          sidecar.istio.io/inject: "true"
          proxy.istio.io/config: '{"holdApplicationUntilProxyStarts":true}'
